name: Deploy GAE
on:
  push:
    tags:
      - crawlV*.*.*-dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Publish app to Google App Engine
        uses: zxyle/publish-gae-action@v2.3.0
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          gae_variables: ${{ secrets.GAE_VARIABLES }}
          gae_config_path: ${{ secrets.CONFIG_PATH }}
      - name: Pulish app to Google App Engine
        run: |
          gcloud auth activate-service-account ${{ secrets.GCP_SA_EMAIL }} --key-file=client-secret.json
          gcloud config set project ${{ secrets.PROJECT_ID }}
          gcloud -q app deploy app.yaml --promote
                
